apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment #name of the microservice
  labels:
    app: hello
spec:
  replicas: 1 #tells deployment how many pods we want to create
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nishchinta/hellodocker:version2
        ports:
        - containerPort: 8080
